---
title: "Chapter 1 Weather Variables"
description: ""
date: "2023-6-11"
execute:
  freeze: false
format:
    revealjs:
        incremental: true
        theme: dark
        shuffle: true
        navigation-mode: grid
        font-size: 17
    html:
        code-fold: true
        code-summary: "Show the code"
        code-block-background: true
---


## Temperature

* Measured using Thermometor
* Kinetic energy of molecules in the air
* indirect measurement of average kinetic energy in the air

## Conversion of Temperature

* K 
  - ⁰C + 273.15⁰
* F 
  - [9/5 * (C)] + 32 
  - Approx: F = (2 * C) + 30


## Tools To Measure Temp

* Thermometer
* Radiosonde
  - Weather Balloon, measure temp high up

## Pressure
* Formula
  - F = p * A
  - Force equals pressure over an area
* Decreases how?
  - Exponentially

## Measuring Pressure
* Barometer (tool)
* Measured in?
  - Hg: mercury, avg at sea levl is 760 mm
  - Milibars (mb): avg at sea level 1013
  - Hecopascals (hPa): equal to milibars
  - psi: 14.6 at sea level

## Pressure Formula Conversion

## Wind:
* How is it noted:
  - In the direction of origin
  - Average over period of time
* Max speed is a "gust"


## Wind Measurement Values
* 1 knot
* equals 1.85 km/hr
* equals 1.15 mph
* Also Beaufort scale

## Measuring Precipitation
*  

## Symbols
